/**
 * 回應訊息類型
 */
export enum SwResponseMessageType {
  TOKEN_HAS_EXPIRED_PLEASE_LOGIN_AGAIN = 'TOKEN_HAS_EXPIRED_PLEASE_LOGIN_AGAIN',
  ACCOUNT_OR_PASSWORD_INCORRECT = 'ACCOUNT_OR_PASSWORD_INCORRECT',
  ACCOUNT_OR_PASSWORD_CAN_NOT_BE_EMPTY = 'ACCOUNT_OR_PASSWORD_CAN_NOT_BE_EMPTY',
  UPLOAD_FAIL = 'UPLOAD_FAIL',
  PASSWORD_ADN_PASSWORD_CONFIRM_ARE_INCONSISTENT = 'PASSWORD_ADN_PASSWORD_CONFIRM_ARE_INCONSISTENT',
  OLD_PASSWORD_ERROR = 'OLD_PASSWORD_ERROR',
  PERMISSION_VERIFICATION_ERROR = 'PERMISSION_VERIFICATION_ERROR',
  ACCOUNT_HAS_ALREADY_BEEN_APPLIED = 'ACCOUNT_HAS_ALREADY_BEEN_APPLIED',
  PHONE_HAS_ALREADY_BEEN_APPLIED = 'PHONE_HAS_ALREADY_BEEN_APPLIED',
  OPERATE_SUCCESS = 'OPERATE_SUCCESS',
  OPERATE_FAIL = 'OPERATE_FAIL',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  ACCOUNT_REPEAT = 'ACCOUNT_REPEAT',
  ACCOUNT_HAS_LOGIN_ON_OTHER_DEVICE = 'ACCOUNT_HAS_LOGIN_ON_OTHER_DEVICE',
  EMAIL_HAS_ALREADY_BEEN_APPLIED = 'EMAIL_HAS_ALREADY_BEEN_APPLIED',
  VALID_FAIL = 'VALID_FAIL'
}
